apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "java-backend1.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "java-backend1.labels" . | nindent 4 }}
data:
  # Application Configuration
  {{- if .Values.configMap }}
  {{- range $key, $value := .Values.configMap }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- else }}
  # Default configuration if configMap values not provided
  APPLICATION_NAME: {{ .Values.app.name | default "java-backend1-user-management" | quote }}
  SPRING_PROFILES_ACTIVE: {{ .Values.springboot.profiles.active | default .Values.app.environment | quote }}
  SERVER_PORT: {{ .Values.service.port | default 8080 | quote }}
  
  # Database Configuration
  DB_HOST: {{ .Values.database.host | quote }}
  DB_PORT: {{ .Values.database.port | default 5432 | quote }}
  DB_NAME: {{ .Values.database.name | quote }}
  DB_USERNAME: {{ .Values.database.username | quote }}
  
  # External Services
  {{- if .Values.externalServices.notificationService }}
  NOTIFICATION_SERVICE_URL: {{ .Values.externalServices.notificationService.url | quote }}
  NOTIFICATION_SERVICE_TIMEOUT: {{ .Values.externalServices.notificationService.timeout | default 5000 | quote }}
  {{- end }}
  
  # JWT Configuration
  {{- if .Values.security.jwt }}
  JWT_EXPIRATION: {{ .Values.security.jwt.expiration | default 3600000 | quote }}
  {{- end }}
  
  # Environment-specific Management Endpoints
  {{- if eq .Values.app.environment "production" }}
  HEALTH_SHOW_DETAILS: "never"
  LOG_LEVEL_ROOT: "ERROR"
  LOG_LEVEL_APP: "WARN"
  {{- else if eq .Values.app.environment "ppr" }}
  HEALTH_SHOW_DETAILS: "never"
  LOG_LEVEL_ROOT: "ERROR"
  LOG_LEVEL_APP: "WARN"
  {{- else if eq .Values.app.environment "sqe" }}
  HEALTH_SHOW_DETAILS: "when-authorized"
  LOG_LEVEL_ROOT: "WARN"
  LOG_LEVEL_APP: "INFO"
  {{- else }}
  HEALTH_SHOW_DETAILS: "always"
  LOG_LEVEL_ROOT: "INFO"
  LOG_LEVEL_APP: "DEBUG"
  {{- end }}
  
  # JPA Configuration based on environment
  {{- if eq .Values.app.environment "production" }}
  JPA_DDL_AUTO: "none"
  JPA_SHOW_SQL: "false"
  {{- else if eq .Values.app.environment "ppr" }}
  JPA_DDL_AUTO: "none"
  JPA_SHOW_SQL: "false"
  {{- else if eq .Values.app.environment "sqe" }}
  JPA_DDL_AUTO: "validate"
  JPA_SHOW_SQL: "false"
  {{- else }}
  JPA_DDL_AUTO: "create-drop"
  JPA_SHOW_SQL: "true"
  {{- end }}
  
  # Database Pool Configuration based on environment
  {{- if eq .Values.app.environment "production" }}
  DB_POOL_SIZE: "20"
  DB_POOL_MIN_IDLE: "10"
  {{- else if eq .Values.app.environment "ppr" }}
  DB_POOL_SIZE: "18"
  DB_POOL_MIN_IDLE: "8"
  {{- else if eq .Values.app.environment "sqe" }}
  DB_POOL_SIZE: "15"
  DB_POOL_MIN_IDLE: "5"
  {{- else }}
  DB_POOL_SIZE: "5"
  DB_POOL_MIN_IDLE: "1"
  {{- end }}
  
  {{- end }}
  
  # Monitoring Configuration
  {{- if .Values.monitoring.enabled }}
  MONITORING_ENABLED: "true"
  PROMETHEUS_ENABLED: "true"
  {{- else }}
  MONITORING_ENABLED: "false"
  PROMETHEUS_ENABLED: "false"
  {{- end }}
  
  # Application Metadata
  APP_VERSION: {{ .Values.app.version | default .Chart.AppVersion | quote }}
  APP_ENVIRONMENT: {{ .Values.app.environment | quote }}
  
---
{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "java-backend1.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "java-backend1.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{- if $value }}
  {{ $key }}: {{ $value }}
  {{- end }}
  {{- end }}
{{- end }}