# Local Development Profile
# Used for local development with developer-friendly settings

spring:
  # JPA/Hibernate configuration for development
  jpa:
    hibernate:
      ddl-auto: create-drop  # Recreate schema on startup (development only)
    show-sql: true          # Show SQL queries in console
    properties:
      hibernate:
        format_sql: true    # Format SQL for readability

# Development server configuration
server:
  port: 8080

# Development logging - more verbose
logging:
  level:
    root: INFO
    com.example.userservice: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Management endpoints - more details for development
management:
  endpoint:
    health:
      show-details: always  # Always show health details in development

# Development-specific app configuration
app:
  security:
    jwt:
      secret: "development-secret-key-not-for-production"
      expiration: 3600000  # 1 hour for development (shorter for testing)
  
  external:
    notification-service:
      url: "http://localhost:3000"
      timeout: 30000  # Longer timeout for development debugging