# Production Environment Profile
# Production-ready configuration with security and performance optimizations

spring:
  # JPA/Hibernate configuration for production
  jpa:
    hibernate:
      ddl-auto: none  # Never auto-create/update schema in production
    show-sql: false   # Never log SQL in production
    properties:
      hibernate:
        format_sql: false
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

# Production logging - minimal and secure
logging:
  level:
    root: ERROR
    com.example.userservice: WARN
    org.springframework.security: ERROR
    org.hibernate.SQL: ERROR
  file:
    name: /var/log/app/application.log
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 30

# Production management endpoints - security focused
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus  # Limited endpoints only
      base-path: /actuator
  endpoint:
    health:
      show-details: never  # Never expose health details in production
  security:
    enabled: true

# Production-specific app configuration
app:
  security:
    jwt:
      # JWT secret MUST be provided via environment variable
      secret: ${JWT_SECRET}
      expiration: ${JWT_EXPIRATION:3600000}  # 1 hour default
  
  external:
    notification-service:
      url: ${NOTIFICATION_SERVICE_URL}
      timeout: ${NOTIFICATION_SERVICE_TIMEOUT:5000}

# Production database optimizations
spring.datasource.hikari:
  maximum-pool-size: ${DB_POOL_SIZE:20}
  minimum-idle: ${DB_POOL_MIN_IDLE:10}
  connection-timeout: 30000
  idle-timeout: 600000
  max-lifetime: 1800000
  leak-detection-threshold: 30000