# Base Configuration for Java Backend 1 - User Management Service
# Common settings shared across all environments

spring:
  application:
    name: java-backend1-user-management
  
  # Default profile (can be overridden by environment variable)
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  
  # Database configuration with environment variable placeholders
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:userdb}
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:password}
    hikari:
      connection-timeout: 20000
      maximum-pool-size: ${DB_POOL_SIZE:10}
      minimum-idle: ${DB_POOL_MIN_IDLE:5}
      idle-timeout: 300000
      max-lifetime: 1200000
      leak-detection-threshold: 60000
  
  # JPA/Hibernate configuration
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:validate}
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false

# Server configuration
server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api

# Management/Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: ${HEALTH_SHOW_DETAILS:when-authorized}
  metrics:
    export:
      prometheus:
        enabled: true

# Logging configuration
logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    com.example.userservice: ${LOG_LEVEL_APP:INFO}
    org.springframework.security: ${LOG_LEVEL_SECURITY:WARN}
    org.hibernate.SQL: ${LOG_LEVEL_SQL:WARN}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Application-specific configuration
app:
  name: "User Management Service"
  version: "@project.version@"
  description: "Handles user registration, authentication, and profile management"
  
  # JWT configuration
  security:
    jwt:
      secret: ${JWT_SECRET:defaultsecret}
      expiration: ${JWT_EXPIRATION:86400000} # 24 hours
  
  # External service URLs (will be overridden by environment)
  external:
    notification-service:
      url: ${NOTIFICATION_SERVICE_URL:http://localhost:3000}
      timeout: ${NOTIFICATION_SERVICE_TIMEOUT:5000}